# Generated by Django 5.1.1 on 2024-12-04 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("band", "0002_band_tour"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tour",
            name="date",
        ),
        migrations.AddField(
            model_name="tour",
            name="end_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="tour",
            name="start_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="tour",
            name="location",
            field=models.CharField(max_length=200),
        ),
    ]
